name: Deploy Repository to AWS
description: Custom Action To Deploy Code to AWS (Lambda)
inputs:
  lambda-name:
    description: "Name of the Lambda"
    required: true
  lambda-role:
    description: "Role of the Lambda"
    required: true
  aws-access-key-id:
    description: "Access Key ID for AWS"
    required: true
  aws-secret-access-key:
    description: "Secret Access key for AWS"
    required: true
  aws-region:
    description: "AWS Region for deployment"
    required: true
    default: "us-east-1"
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - run: |
         chmod +x ./scripts/create_claudia_config.sh
         ./scripts/create_claudia_config.sh ${{ inputs.lambda-name }} ${{ inputs.lambda-role }} ${{ inputs.aws-region }}
      shell: bash
    - run: claudia update
      shell: bash